apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: denshnitest.azurecr.io/react/denshi:latest
        ports:
        - containerPort: 80
    imagePullSecrets:
    - name: acr-secret

    